### ISSUE TITLE
what's the relationship between state1 and state2 ?

### ISSUE THREAD

**Issue by linshoa** [amitz25/PCCoder#1]
Hi~
I have read your paper recently, it was an amazing work. But I just confused that what the relationship between state1 and state2 was?
From Fig1, Fig2, I think state1 means  all the variables including intermediate variable in example1 and state2 is another example.
But from Sec.2, 

>  To that end we define the state of a program as the sequence of all the variable values acquired thus far, starting with the program’s input, and concatenated with the desired output. Before performing any line of code, the state contains the inputs and the output. After each line of code, a new variable is added to the state.

I think state2 is an new one respects to state1. I mean, after a line of code, we get state2 from state1.

Hope for your reply~

**Comment by amitz25** [comment]
Hi,

Thank you for your interest in our work.
There is a separate state for each input/output sample. So in figure 1, state 1 refers to the program's intermediate state when run on the first I/O sample (up until line 3), and state 2 refers to the program's  state when run on the second sample.

This also aligns with the explanation in the sentence you quoted: each state represents the program's execution on a single input/output sample. Note that we later said "inputs" and not "input" because a single input/output sample can have more than one input. 
E.g., this is a valid I/O sample in our DSL:
Inputs: [0], [1, 1, 0, 2, 0]
Output: 2

I refer you to section 2 of our supplementary for more demonstrations of programs and their I/O samples. The supplementary can be found here:
http://papers.nips.cc/paper/7479-automatic-program-synthesis-of-long-programs-with-a-learned-garbage-collector

If you have further questions, feel free to ask me via email
amit.zhr@gmail.com
